# -*- coding: utf-8 -*-
"""Barcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4pZjiNxQVG42CPALqSu2QqTjDw1P3I_
"""

# Importing necessaary libraries
! pip install pyzbar
!sudo apt-get install libzbar0

import cv2
from pyzbar import pyzbar

def detect_barcode(image_path):
    # Preprocessing (Resize, Normalization, etc.)
    image = cv2.imread(image_path)
    image = cv2.resize(image, (800, 600))  # Resize the image
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)  # Convert to grayscale

    # Feature Extraction (Edges, Lines, Shapes, etc.)
    edges = cv2.Canny(image, 50, 150)  # Apply Canny edge detection

    # Barcode Region Detection (Bounding Box, etc.)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    for contour in contours:
        x, y, w, h = cv2.boundingRect(contour)
        if w > 100 and h > 100:  # Filter out small contours
            # Barcode Decoding (1D/2D barcode algorithms)
            barcode = pyzbar.decode(image[y:y+h, x:x+w])
            if barcode:
                # Postprocessing (Error correction, etc.)
                barcode_data = barcode[0].data.decode("utf-8")
                return barcode_data

    return None

# Example usage
image_path = "Barcode.jpg"
barcode_data = detect_barcode(image_path)
if barcode_data:
    print("Detected barcode data:", barcode_data)
else:
    print("No barcode detected")

